faf

diff --git a/my_which b/my_which
--- a/my_which
+++ b/my_which
@@ -1,37 +1,43 @@
-# INFO: Which takes a list of names and looks for the files 
-# which would be executed had these names been given as commands. 
-# Each argument is searched for along the user's path.
-# If  the -a flag is give, which will return a list of 
-# all matches instead of just the  first match.
+#!/bin/sh
 
+# INFO: 'which' takes a list of command names and searches the user's PATH 
+# to identify the full path of executables matching those commands. 
+# If  the '-a' option is provided, all matching paths are displayed, 
+# otherwise only the first match is shown
 
-# Is option -a enabled?
+# Flag to track whether '-a' option (list all matches) is enabled
 opt_a=0
 
-# Variable to record how many names were resolved
+# Counter to track how many commands were successfully resolved
 found=0
 
-# Retreieve the arguments used with which command
+# Store arguments passed to the script
 args="$@"
 
-# Retrieve the number of arguments used with program 
+# Store number of arguments passed to the script
 num_args=$#
 
 
-# Usage Error Message
+# Function: Display usage information and exit
 error_usage(){
 	#echo "usage: $(basename $0) [-a] name ..." >&2
 	echo "usage: which [-a] name ..." >&2
 	exit 1
 }
 
-# Check input arguments 
+
+# Function: Display 'Command not found' and exit
+error_option(){
+	echo "which: $arg: Command not found." >&2
+
+}
+
+# Function: Parse and validate command-line arguments 
 check_args(){
-	# Get input argumnts
-	# By adding: before a, I am telling getopts that I want to take control of flags that are not in the list I set
+        # Process options. The ':' before 'a' allows manual handling of unknown flags
 	while getopts ":a" options; do
 		case "${options}" in
-			# if -a option is enabled
+			# if '-a' option is enabled
 			a) 
 		   	  opt_a=1
 		   	  ;;
@@ -92,8 +98,6 @@ main_function(){
 					echo "$arg"
 					found=$found+1
 					is_found=1
-				#else
-				#	echo "$arg: Command not found." >&2
 				fi;;
 			*)
 				for dir in $dirs; do
@@ -109,8 +113,7 @@ main_function(){
 
 		# A diagnostic is given if an executable file with the argument name was not found in the path
 		if [ $is_found -eq 0 ]; then
-			#echo "$(basename $0): $arg: Command not found." >&2
-			echo "which: $arg: Command not found." >&2
+			error_option()
 		fi
 	done
 
